import React, { useRef, useState } from 'react';
import { CheckCircle, Download, FileSpreadsheet, Upload } from 'lucide-react';
import { AuthUser, ParsedLeadRow } from '../../types';
import { api } from '../../lib/api';
import { downloadSampleTemplate, parseExcelOrCsv } from '../../lib/excelParser';
import { companyName } from './HrDashboard';

export const HrLeadUpload: React.FC<{ user: AuthUser; telecallers: AuthUser[]; onComplete: () => Promise<boolean>; onViewTelecaller: (id: string) => void }> = ({ user, telecallers, onComplete, onViewTelecaller }) => {
  const input = useRef<HTMLInputElement>(null); const [telecallerId,setTelecallerId]=useState(''); const [rows,setRows]=useState<ParsedLeadRow[]>([]); const [invalid,setInvalid]=useState(0); const [file,setFile]=useState(''); const [busy,setBusy]=useState(false); const [result,setResult]=useState<{imported:number;skipped:number;invalid:number;name:string;id:string}|null>(null); const [error,setError]=useState('');
  const selected=telecallers.find(tc=>tc.id===telecallerId);
  const choose=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setError('');try{const parsed=await parseExcelOrCsv(f,user.brandAccess==='APNI_ESTATE'?'APNI_ESTATE':'APNI_VIDYA');setRows(parsed.validRows);setInvalid(parsed.invalidRows.length);setFile(parsed.fileName)}catch(err:any){setError(err.message)}};
  const upload=async()=>{if(!selected||!rows.length)return;setBusy(true);setError('');try{const res=await api.importLeads(rows,selected.id,user.brandAccess==='APNI_ESTATE'?'APNI_ESTATE':'APNI_VIDYA');if(res.assignedCount!==res.importedCount||res.assignedTelecallerId!==selected.id)throw new Error('Import verification failed: uploaded leads were not assigned to the selected telecaller.');if(!await onComplete())throw new Error('Leads were imported, but the dashboard refresh failed. Please retry the refresh.');setResult({imported:res.importedCount,skipped:res.failedCount,invalid,name:selected.name,id:selected.id});setRows([])}catch(err:any){setError(err.message||'Upload failed. Please check the file and try again.')}finally{setBusy(false)}};
  if(result)return <div className="max-w-3xl mx-auto p-5 sm:p-10"><div className="bg-white border border-slate-200 rounded-3xl p-6 sm:p-10 text-center"><CheckCircle className="w-14 h-14 text-emerald-500 mx-auto"/><h1 className="text-2xl font-bold mt-5">Upload completed</h1><div className="grid grid-cols-3 gap-3 mt-7"><div className="bg-emerald-50 rounded-xl p-3"><b className="block text-2xl text-emerald-700">{result.imported}</b><span className="text-xs text-slate-600">Imported</span></div><div className="bg-amber-50 rounded-xl p-3"><b className="block text-2xl text-amber-700">{result.skipped}</b><span className="text-xs text-slate-600">Skipped</span></div><div className="bg-slate-50 rounded-xl p-3"><b className="block text-2xl">{result.invalid}</b><span className="text-xs text-slate-600">Invalid</span></div></div><p className="text-slate-500 mt-6">Assigned to</p><p className="font-bold text-lg mt-1">{result.name}</p><button onClick={()=>onViewTelecaller(result.id)} className="mt-7 bg-blue-600 text-white rounded-xl px-5 py-3 font-semibold">View Telecaller Leads</button></div></div>;
  return <div className="max-w-4xl mx-auto p-5 sm:p-8 space-y-6"><div><p className="text-sm font-semibold text-blue-600">{companyName(user.brandAccess)}</p><h1 className="text-3xl font-bold text-slate-900">Upload leads</h1><p className="text-slate-500 mt-2">Choose whose sheet this is, preview it, then upload.</p></div>{error&&<div className="bg-rose-50 text-rose-700 p-4 rounded-xl">{error}</div>}
    <div className="bg-white border rounded-2xl p-6"><label htmlFor="upload-telecaller" className="font-bold text-slate-900">1. Select Telecaller</label><select id="upload-telecaller" value={telecallerId} onChange={e=>setTelecallerId(e.target.value)} className="mt-3 w-full border rounded-xl p-3"><option value="">Select telecaller</option>{telecallers.filter(t=>t.isActive).map(t=><option key={t.id} value={t.id}>{t.name} ({t.loginId})</option>)}</select>{telecallers.length===0&&<p className="text-sm text-amber-700 mt-3">No telecallers yet. Create your first telecaller before uploading leads.</p>}</div>
    <div className="bg-white border rounded-2xl p-6"><div className="flex justify-between"><label className="font-bold text-slate-900">2. Choose Excel file</label><button onClick={()=>downloadSampleTemplate(user.brandAccess==='APNI_ESTATE'?'APNI_ESTATE':'APNI_VIDYA')} className="text-sm text-blue-600 flex gap-1"><Download className="w-4"/>Sample format</button></div><input ref={input} type="file" accept=".xlsx,.xls,.csv" onChange={choose} className="hidden"/><button disabled={!telecallerId} onClick={()=>input.current?.click()} className="mt-4 w-full border-2 border-dashed rounded-2xl p-10 disabled:opacity-40"><FileSpreadsheet className="w-10 h-10 text-blue-600 mx-auto"/><p className="font-semibold mt-3">{file||'Choose .xlsx, .xls or .csv'}</p><p className="text-sm text-slate-500 mt-1">Required: Name and Phone. Optional: City, Source and Notes.</p></button></div>
    {rows.length>0&&<div className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">3. Preview ({rows.length} valid rows)</h2>{invalid>0&&<p className="text-sm text-amber-700 mt-1">{invalid} invalid rows will be skipped.</p>}</div><div className="max-h-72 overflow-auto divide-y">{rows.slice(0,100).map((r,i)=><div key={`${r.phone}-${i}`} className="grid grid-cols-2 sm:grid-cols-3 gap-2 p-3 text-sm"><span className="font-semibold">{r.name}</span><span>{r.phone}</span><span className="text-slate-500">{r.city||'—'}</span></div>)}</div><div className="p-5 bg-slate-50"><p className="font-bold mb-3">4. Upload & Assign</p><button disabled={busy||!selected} onClick={upload} className="w-full bg-blue-600 text-white rounded-xl p-4 font-bold disabled:opacity-50"><Upload className="inline w-5 mr-2"/>{busy?'Uploading…':`Upload ${rows.length} Leads to ${selected?.name||'Selected Telecaller'}`}</button></div></div>}
  </div>;
};
