import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, CheckCircle2, Clock, KeyRound, MapPin, Phone, Plus, Power, Users } from 'lucide-react';
import { api } from '../../lib/api';
import { AdminMetrics, AuthUser, BusinessBrand, Lead } from '../../types';
import { PasswordResetModal } from '../common/PasswordResetModal';

const names: Record<BusinessBrand, string> = { APNI_VIDYA: 'Apni Vidya', APNI_ESTATE: 'Apni Estate' };
const converted = new Set(['ENROLLED', 'CLOSED', 'SALE']);
const dateToday = () => new Date().toISOString().slice(0, 10);
const labelStatus = (value: string) => value.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase());

type Metric = { label: string; value: number; icon: React.ReactNode };
const MetricCards = ({ items }: { items: Metric[] }) => <div className="grid grid-cols-2 lg:grid-cols-3 gap-3 sm:gap-4">{items.map((item) => <div key={item.label} className="bg-white border border-slate-200 rounded-2xl p-4 sm:p-5"><span className="text-blue-600">{item.icon}</span><b className="block text-2xl sm:text-3xl mt-3">{item.value}</b><span className="text-xs sm:text-sm text-slate-500">{item.label}</span></div>)}</div>;

export const OwnerPortal: React.FC<{ tab: string; leads: Lead[]; telecallers: AuthUser[]; refresh: () => void }> = ({ tab, leads, telecallers, refresh }) => {
  const [hrs, setHrs] = useState<AuthUser[]>([]);
  const [metrics, setMetrics] = useState<Record<string, AdminMetrics | null>>({});
  const [brand, setBrand] = useState<BusinessBrand | null>(null);
  const [viewHr, setViewHr] = useState<AuthUser | null>(null);
  const [viewTc, setViewTc] = useState<AuthUser | null>(null);
  const [form, setForm] = useState({ name: '', loginId: '', password: '', phone: '', email: '', brandAccess: 'APNI_VIDYA' as BusinessBrand });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [resetHr, setResetHr] = useState<AuthUser | null>(null);

  const load = async () => {
    setError('');
    const [h, v, e] = await Promise.allSettled([api.getHrs(), api.getAdminPerformance('APNI_VIDYA'), api.getAdminPerformance('APNI_ESTATE')]);
    if (h.status === 'fulfilled') setHrs(h.value); else setError(h.reason?.message || 'Unable to load HR accounts.');
    if (v.status === 'fulfilled') setMetrics((current) => ({ ...current, APNI_VIDYA: v.value.metrics }));
    if (e.status === 'fulfilled') setMetrics((current) => ({ ...current, APNI_ESTATE: e.value.metrics }));
  };
  useEffect(() => { load(); }, []);
  useEffect(() => { setBrand(null); setViewHr(null); setViewTc(null); }, [tab]);

  const company = (companyBrand: BusinessBrand) => {
    const companyLeads = leads.filter((lead) => lead.brand === companyBrand);
    const backend = metrics[companyBrand];
    return {
      leads: companyLeads,
      callers: telecallers.filter((user) => user.brandAccess === companyBrand),
      hrs: hrs.filter((user) => user.brandAccess === companyBrand),
      total: backend?.totalLeads ?? companyLeads.length,
      calls: backend?.callsToday ?? companyLeads.filter((lead) => lead.lastCallAt?.startsWith(dateToday())).length,
      interested: backend?.interested ?? companyLeads.filter((lead) => lead.status === 'INTERESTED').length,
      followUps: backend?.todayFollowUps ?? companyLeads.filter((lead) => lead.activeFollowUp?.dueDate === dateToday()).length,
      conversions: companyLeads.filter((lead) => converted.has(lead.status)).length,
    };
  };
  const companies = useMemo(() => ({ APNI_VIDYA: company('APNI_VIDYA'), APNI_ESTATE: company('APNI_ESTATE') }), [leads, telecallers, hrs, metrics]);
  const callerRows = (companyBrand: BusinessBrand) => companies[companyBrand].callers.map((caller) => {
    const assigned = companies[companyBrand].leads.filter((lead) => lead.assignedTo === caller.id);
    return { caller, assigned, called: assigned.filter((lead) => lead.totalCallsCount > 0).length, interested: assigned.filter((lead) => lead.status === 'INTERESTED').length, followUps: assigned.filter((lead) => lead.activeFollowUp).length };
  });

  if (viewTc) {
    const companyBrand = viewTc.brandAccess as BusinessBrand;
    const assigned = leads.filter((lead) => lead.assignedTo === viewTc.id);
    const called = assigned.filter((lead) => lead.totalCallsCount > 0).length;
    return <div className="max-w-6xl mx-auto p-5 sm:p-8 space-y-6"><button onClick={() => setViewTc(null)} className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><ArrowLeft className="w-4 h-4" />Back to {names[companyBrand]}</button><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><p className="text-sm font-semibold text-blue-600">Telecaller monitoring</p><h1 className="text-3xl font-bold mt-1">{viewTc.name}</h1><p className="text-slate-500 mt-1">{names[companyBrand]}</p></div><span className={`w-fit rounded-full px-3 py-1 text-sm font-semibold ${viewTc.isActive ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{viewTc.isActive ? 'Active' : 'Inactive'}</span></div><MetricCards items={[{ label: 'Total Leads', value: assigned.length, icon: <Users /> }, { label: 'Called', value: called, icon: <Phone /> }, { label: 'Pending', value: assigned.length - called, icon: <Clock /> }, { label: 'Interested', value: assigned.filter((lead) => lead.status === 'INTERESTED').length, icon: <CheckCircle2 /> }, { label: 'Follow-ups', value: assigned.filter((lead) => lead.activeFollowUp).length, icon: <Clock /> }]} /><section className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Assigned leads</h2><p className="text-sm text-slate-500 mt-1">Read-only monitoring view</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{['Name', 'Phone', 'Status', 'Last Call', 'Follow-up'].map((item) => <th key={item} className="text-left px-5 py-3">{item}</th>)}</tr></thead><tbody className="divide-y">{assigned.map((lead) => <tr key={lead.id}><td className="px-5 py-4 font-semibold">{lead.name}</td><td className="px-5 py-4">{lead.phone}</td><td className="px-5 py-4">{labelStatus(lead.status)}</td><td className="px-5 py-4">{lead.lastCallAt ? new Date(lead.lastCallAt).toLocaleDateString() : 'Not called'}</td><td className="px-5 py-4">{lead.activeFollowUp ? `${lead.activeFollowUp.dueDate} ${lead.activeFollowUp.dueTime}` : 'None'}</td></tr>)}{!assigned.length && <tr><td colSpan={5} className="p-8 text-center text-slate-500">No leads are assigned to this telecaller.</td></tr>}</tbody></table></div></section></div>;
  }

  if (viewHr) {
    const companyBrand = viewHr.brandAccess as BusinessBrand;
    const data = companies[companyBrand];
    return <div className="max-w-6xl mx-auto p-5 sm:p-8 space-y-6"><button onClick={() => setViewHr(null)} className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><ArrowLeft className="w-4 h-4" />Back to {names[companyBrand]}</button><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><p className="text-sm font-semibold text-blue-600">HR monitoring</p><h1 className="text-3xl font-bold mt-1">{viewHr.name}</h1><p className="text-slate-500 mt-1">{names[companyBrand]}</p></div><span className={`w-fit rounded-full px-3 py-1 text-sm font-semibold ${viewHr.isActive ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{viewHr.isActive ? 'Active' : 'Inactive'}</span></div><MetricCards items={[{ label: 'Telecallers', value: data.callers.length, icon: <Users /> }, { label: 'Total Leads', value: data.total, icon: <Users /> }, { label: 'Calls Today', value: data.calls, icon: <Phone /> }, { label: 'Follow-ups', value: data.followUps, icon: <Clock /> }]} /><section className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Company team</h2><p className="text-sm text-slate-500 mt-1">Telecallers within this HR company scope</p></div><div className="divide-y">{callerRows(companyBrand).map((row) => <button key={row.caller.id} onClick={() => setViewTc(row.caller)} className="w-full p-5 grid grid-cols-2 md:grid-cols-5 gap-3 text-left hover:bg-slate-50"><span className="font-semibold">{row.caller.name}</span><span>{row.assigned.length} leads</span><span>{row.called} called</span><span>{row.followUps} follow-ups</span><span className={row.caller.isActive ? 'text-emerald-700' : 'text-rose-700'}>{row.caller.isActive ? 'Active' : 'Inactive'}</span></button>)}</div></section></div>;
  }

  if (brand) {
    const data = companies[brand];
    return <div className="max-w-6xl mx-auto p-5 sm:p-8 space-y-6"><button onClick={() => setBrand(null)} className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600"><ArrowLeft className="w-4 h-4" />All Companies</button><div><p className="text-sm font-semibold text-blue-600">Company overview</p><h1 className="text-3xl font-bold mt-1">{names[brand]}</h1><p className="text-slate-500 mt-2">Company activity and team progress at a glance.</p></div><MetricCards items={[{ label: 'Total Leads', value: data.total, icon: <Users /> }, { label: 'Telecallers', value: data.callers.length, icon: <Users /> }, { label: 'Calls Today', value: data.calls, icon: <Phone /> }, { label: 'Interested', value: data.interested, icon: <CheckCircle2 /> }, { label: 'Follow-ups', value: data.followUps, icon: <Clock /> }, { label: 'Converted', value: data.conversions, icon: <CheckCircle2 /> }]} /><section className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Company HR</h2></div>{data.hrs.length ? <div className="divide-y">{data.hrs.map((hr) => <button key={hr.id} onClick={() => setViewHr(hr)} className="w-full p-5 flex items-center justify-between gap-4 text-left hover:bg-slate-50"><span><b className="block">{hr.name}</b><small className="text-slate-500">{names[brand]}</small></span><span className="flex items-center gap-3"><span className={hr.isActive ? 'text-emerald-700' : 'text-rose-700'}>{hr.isActive ? 'Active' : 'Inactive'}</span><ArrowRight className="w-4 h-4" /></span></button>)}</div> : <p className="p-7 text-slate-500">No HR accounts are assigned to this company yet.</p>}</section><section className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b"><h2 className="font-bold">Telecaller Performance</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-sm"><thead className="bg-slate-50 text-slate-500"><tr>{['Name', 'Total Leads', 'Called', 'Pending', 'Interested', 'Follow-ups', 'Status'].map((item) => <th key={item} className="text-left px-5 py-3">{item}</th>)}</tr></thead><tbody className="divide-y">{callerRows(brand).map((row) => <tr key={row.caller.id} onClick={() => setViewTc(row.caller)} className="cursor-pointer hover:bg-slate-50"><td className="px-5 py-4 font-semibold text-blue-700">{row.caller.name}</td><td className="px-5 py-4">{row.assigned.length}</td><td className="px-5 py-4">{row.called}</td><td className="px-5 py-4">{row.assigned.length - row.called}</td><td className="px-5 py-4">{row.interested}</td><td className="px-5 py-4">{row.followUps}</td><td className={`px-5 py-4 ${row.caller.isActive ? 'text-emerald-700' : 'text-rose-700'}`}>{row.caller.isActive ? 'Active' : 'Inactive'}</td></tr>)}</tbody></table></div></section></div>;
  }

  const create = async (event: React.FormEvent) => { event.preventDefault(); setError(''); setSuccess(''); try { await api.createHr(form); setSuccess('HR created successfully.'); setForm({ ...form, name: '', loginId: '', password: '', phone: '', email: '' }); await load(); refresh(); } catch (caught: any) { setError(caught.message); } };
  const toggle = async (hr: AuthUser) => { await api.updateHr(hr.id, { isActive: !hr.isActive }); await load(); };
  const updateHrPassword = async (password: string) => { if (!resetHr) return; await api.resetHrPassword(resetHr.id, password); setResetHr(null); setSuccess('Password updated successfully.'); };

  if (tab === 'hrs') return <div className="max-w-6xl mx-auto p-5 sm:p-8 space-y-6"><div><h1 className="text-3xl font-bold">HR Management</h1><p className="text-slate-500 mt-2">Create and manage company HR accounts.</p></div>{error && <p className="bg-rose-50 text-rose-700 p-3 rounded-xl">{error}</p>}{success && <p className="bg-emerald-50 text-emerald-800 p-4 rounded-xl font-semibold">{success}</p>}<div className="grid lg:grid-cols-5 gap-6"><form onSubmit={create} className="lg:col-span-2 bg-white border rounded-2xl p-6 space-y-4"><h2 className="font-bold text-xl flex gap-2"><Plus />Create HR</h2>{['name', 'loginId', 'password', 'phone', 'email'].map((key) => <input key={key} type={key === 'password' ? 'password' : 'text'} minLength={key === 'password' ? 8 : undefined} required={['name', 'loginId', 'password'].includes(key)} placeholder={key === 'loginId' ? 'Login ID' : key[0].toUpperCase() + key.slice(1)} value={(form as any)[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="w-full border rounded-xl p-3" />)}<select value={form.brandAccess} onChange={(event) => setForm({ ...form, brandAccess: event.target.value as BusinessBrand })} className="w-full border rounded-xl p-3"><option value="APNI_VIDYA">Apni Vidya</option><option value="APNI_ESTATE">Apni Estate</option></select><button className="w-full bg-blue-600 text-white p-3 rounded-xl font-bold">Create HR</button></form><div className="lg:col-span-3 bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b font-bold">HR Accounts</div><div className="divide-y">{hrs.map((hr) => <div key={hr.id} className="p-5 flex items-center justify-between gap-3"><button onClick={() => setViewHr(hr)} className="text-left"><p className="font-bold">{hr.name}</p><p className="text-sm text-slate-500">{hr.loginId} · {names[hr.brandAccess as BusinessBrand]}</p><span className={`text-xs ${hr.isActive ? 'text-emerald-600' : 'text-rose-600'}`}>{hr.isActive ? 'Active' : 'Inactive'}</span></button><div className="flex gap-2"><button title="Reset password" onClick={() => setResetHr(hr)} className="border rounded-lg p-2"><KeyRound /></button><button title={hr.isActive ? 'Deactivate' : 'Activate'} onClick={() => toggle(hr)} className="border rounded-lg p-2"><Power /></button></div></div>)}</div></div></div>{resetHr && <PasswordResetModal user={resetHr} onCancel={() => setResetHr(null)} onUpdate={updateHrPassword} />}</div>;

  if (tab === 'reports') {
    const statuses: Array<{ status: string; count: number }> = Array.from(new Set<string>(leads.map((lead) => String(lead.status)))).map((status) => ({ status, count: leads.filter((lead) => lead.status === status).length })).sort((a, b) => b.count - a.count);
    const cityCounts = new Map<string, number>();
    leads.forEach((lead) => { const city = lead.city?.trim(); if (city) cityCounts.set(city, (cityCounts.get(city) || 0) + 1); });
    const cities = [...cityCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5);
    return <div className="max-w-6xl mx-auto p-5 sm:p-8 space-y-6"><div><h1 className="text-3xl font-bold">Reports</h1><p className="text-slate-500 mt-2">Simple company and team performance summaries.</p></div><section className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b font-bold">Company Performance</div><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-slate-50"><tr>{['Company', 'Leads', 'Telecallers', 'Calls Today', 'Interested', 'Follow-ups', 'Converted'].map((item) => <th key={item} className="text-left px-5 py-3">{item}</th>)}</tr></thead><tbody>{(['APNI_VIDYA', 'APNI_ESTATE'] as BusinessBrand[]).map((companyBrand) => { const data = companies[companyBrand]; return <tr key={companyBrand} className="border-t"><td className="px-5 py-4 font-semibold">{names[companyBrand]}</td><td className="px-5 py-4">{data.total}</td><td className="px-5 py-4">{data.callers.length}</td><td className="px-5 py-4">{data.calls}</td><td className="px-5 py-4">{data.interested}</td><td className="px-5 py-4">{data.followUps}</td><td className="px-5 py-4">{data.conversions}</td></tr>; })}</tbody></table></div></section><div className="grid lg:grid-cols-2 gap-5"><section className="bg-white border rounded-2xl p-5"><h2 className="font-bold">Lead Status Summary</h2><div className="mt-4 divide-y">{statuses.map((item) => <div key={item.status} className="py-3 flex justify-between"><span>{labelStatus(item.status)}</span><b>{item.count}</b></div>)}</div></section><section className="bg-white border rounded-2xl p-5"><h2 className="font-bold">Top Cities</h2>{cities.length ? <div className="mt-4 divide-y">{cities.map(([city, count]) => <div key={city} className="py-3 flex justify-between"><span>{city}</span><b>{count}</b></div>)}</div> : <p className="text-slate-500 mt-4">No city information has been collected yet.</p>}</section></div><section className="bg-white border rounded-2xl p-6"><MapPin className="text-blue-600" /><h2 className="text-xl font-bold mt-4">Location Reporting</h2><p className="text-slate-500 mt-2 max-w-2xl">State-level reporting will become available once normalized state information is collected with lead uploads.</p></section></div>;
  }

  const companyCard = (companyBrand: BusinessBrand) => { const data = companies[companyBrand]; return <button onClick={() => setBrand(companyBrand)} className="w-full text-left bg-white border rounded-2xl p-5 sm:p-6 hover:border-blue-400 hover:shadow-md transition"><div className="flex justify-between gap-4"><div><p className="text-sm font-semibold text-blue-600">Company</p><h2 className="text-2xl font-bold mt-1">{names[companyBrand]}</h2></div><div className="flex items-center gap-2 text-sm font-semibold text-blue-600">View <ArrowRight className="w-4 h-4" /></div></div><div className="grid grid-cols-2 sm:grid-cols-3 gap-4 mt-6 text-sm">{[['Total Leads', data.total], ['Telecallers', data.callers.length], ['Calls Today', data.calls], ['Interested', data.interested], ['Follow-ups Today', data.followUps], ['Active HR', data.hrs.filter((hr) => hr.isActive).length]].map(([item, value]) => <div key={String(item)}><b className="text-xl block">{value}</b><span className="text-slate-500">{item}</span></div>)}</div></button>; };
  const calls = (metrics.APNI_VIDYA?.callsToday || 0) + (metrics.APNI_ESTATE?.callsToday || 0);
  const followUps = (metrics.APNI_VIDYA?.todayFollowUps || 0) + (metrics.APNI_ESTATE?.todayFollowUps || 0);
  return <div className="max-w-6xl mx-auto p-5 sm:p-8 space-y-7"><div><p className="text-sm font-semibold text-blue-600">Owner overview</p><h1 className="text-3xl font-bold">Both companies, one clear view</h1><p className="text-slate-500 mt-2">Monitor business activity without entering daily calling workflows.</p></div><MetricCards items={[{ label: 'Total Leads', value: leads.length, icon: <Users /> }, { label: 'Total Telecallers', value: telecallers.length, icon: <Users /> }, { label: 'Calls Today', value: calls, icon: <Phone /> }, { label: 'Interested Leads', value: leads.filter((lead) => lead.status === 'INTERESTED').length, icon: <CheckCircle2 /> }, { label: 'Follow-ups Today', value: followUps, icon: <Clock /> }, { label: 'Converted Leads', value: leads.filter((lead) => converted.has(lead.status)).length, icon: <CheckCircle2 /> }]} /><div className="grid md:grid-cols-2 gap-5">{companyCard('APNI_VIDYA')}{companyCard('APNI_ESTATE')}</div></div>;
};
