import React from 'react';
import { ArrowRight, Clock, Phone, Users } from 'lucide-react';
import { AuthUser, Lead } from '../../types';
import { companyName } from '../hr/HrDashboard';

export const SimpleTelecallerHome: React.FC<{ user:AuthUser; leads:Lead[]; onStart:(lead:Lead)=>void; onLead:(lead:Lead)=>void; onNavigate:(tab:string)=>void }> = ({user,leads,onStart,onLead,onNavigate}) => {
 const today=new Date().toISOString().slice(0,10); const called=leads.filter(l=>l.totalCallsCount>0).length; const pending=leads.filter(l=>l.status==='NEW').length; const due=leads.filter(l=>l.activeFollowUp?.dueDate===today); const next=due[0]||leads.find(l=>l.status==='NEW'); const greeting=new Date().getHours()<12?'Good morning':new Date().getHours()<17?'Good afternoon':'Good evening';
 return <div className="max-w-5xl mx-auto p-4 sm:p-8 space-y-6"><div><p className="text-sm font-semibold text-blue-600">{companyName(user.brandAccess)}</p><h1 className="text-3xl font-bold text-slate-900 mt-1">{greeting}, {user.name}</h1><p className="text-slate-500 mt-2">{next?'Your next call is ready.':leads.length?'All pending calls are complete.':'No leads are assigned to you yet.'}</p></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['My Leads',leads.length,<Users/>],['Called',called,<Phone/>],['Pending',pending,<Phone/>],['Follow-ups Today',due.length,<Clock/>]].map(([l,v,i])=><div key={String(l)} className="bg-white border rounded-2xl p-4"><span className="text-blue-600">{i}</span><b className="block text-3xl mt-3">{v}</b><span className="text-sm text-slate-500">{l}</span></div>)}</div><button disabled={!next} onClick={()=>next&&onStart(next)} className="w-full bg-blue-600 disabled:bg-slate-300 text-white rounded-2xl p-5 text-lg font-bold flex justify-center items-center gap-3"><Phone/>{next?'START CALLING':leads.length?'ALL CALLS COMPLETED':'NO LEADS ASSIGNED'}{next&&<ArrowRight/>}</button><section className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b flex justify-between"><h2 className="font-bold">Today’s follow-ups</h2><button onClick={()=>onNavigate('followups')} className="text-blue-600 text-sm">View all</button></div>{due.length===0?<p className="p-6 text-slate-500">No follow-ups due today.</p>:due.slice(0,5).map(l=><button key={l.id} onClick={()=>onLead(l)} className="w-full p-4 border-b last:border-0 flex justify-between text-left"><span><b className="block">{l.name}</b><small className="text-slate-500">{l.phone}</small></span><span className="font-semibold">{l.activeFollowUp?.dueTime}</span></button>)}</section><section className="bg-white border rounded-2xl overflow-hidden"><div className="p-5 border-b flex justify-between"><h2 className="font-bold">My leads</h2><button onClick={()=>onNavigate('leads')} className="text-blue-600 text-sm">View all</button></div>{leads.length===0?<p className="p-6 text-slate-500">No assigned leads yet. Please ask your HR manager to assign leads.</p>:leads.slice(0,5).map(l=><button key={l.id} onClick={()=>onLead(l)} className="w-full p-4 border-b last:border-0 flex justify-between text-left"><span><b className="block">{l.name}</b><small className="text-slate-500">{l.phone}</small></span><span className="text-sm">{l.status.replaceAll('_',' ')}</span></button>)}</section></div>;
};
